server:
  port: 8120 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: guli-oss # 服务名

aliyun:
  oss:
    file:
      endpoint: oss-cn-shanghai.aliyuncs.com
      keyid: LTAI4Fo6sRSrqyQLVBc6jgtz
      keysecret: FKcTuM2tOgqflxnYEILIwh3Q8Ywbv6
      #bucket可以在控制台创建，也可以使用java代码创建，注意先测试bucket是否已被占用
      bucketname: online-education-guli